#!/usr/bin/env bash
# Run the caller-signed EVM agent against protocol/scripts/local_node_agents.sh.
#
# Usage:
#   ./scripts/local-evm-agent.sh start
#   ./scripts/local-evm-agent.sh stop|status|logs|config

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

fail() { printf 'local-evm-agent: %s\n' "$*" >&2; exit 1; }
info() { printf 'local-evm-agent: %s\n' "$*"; }

mode="start"
chain_id="${EVM_AGENT_LOCAL_CHAIN_ID:-svp-2517-1}"
grpc_addr="${EVM_AGENT_LOCAL_GRPC:-127.0.0.1:9090}"
comet_rpc="${EVM_AGENT_LOCAL_COMET_RPC:-http://127.0.0.1:26657}"
evm_rpc="${EVM_AGENT_LOCAL_EVM_RPC:-http://127.0.0.1:8545}"
indexer="${EVM_AGENT_LOCAL_INDEXER:-http://127.0.0.1:3002}"
listen_addr="${EVM_AGENT_LOCAL_LISTEN:-127.0.0.1:8083}"
public_url="${EVM_AGENT_LOCAL_PUBLIC_URL:-http://localhost:8083}"
protocol_dir="${EVM_AGENT_LOCAL_PROTOCOL_DIR:-}"
local_chain_script="${EVM_AGENT_LOCAL_CHAIN_SCRIPT:-}"
local_chain_home="${EVM_AGENT_LOCAL_CHAIN_HOME:-${DYDX_HOME:-$HOME/.svpchain-agents}}"
skip_build=0

usage() {
  sed -n '2,/^set -euo pipefail/p' "${BASH_SOURCE[0]}" | sed -n '/^#/p' | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    start|stop|status|logs|config) mode="$1"; shift ;;
    --chain-id) chain_id="${2:-}"; shift 2 ;;
    --grpc-addr) grpc_addr="${2:-}"; shift 2 ;;
    --comet-rpc) comet_rpc="${2:-}"; shift 2 ;;
    --evm-rpc) evm_rpc="${2:-}"; shift 2 ;;
    --indexer) indexer="${2:-}"; shift 2 ;;
    --listen) listen_addr="${2:-}"; shift 2 ;;
    --public-url) public_url="${2:-}"; shift 2 ;;
    --skip-build) skip_build=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) fail "unknown argument: $1" ;;
  esac
done

public_url="${public_url%/}"
state_dir="${REPO_DIR}/build/local-evm-agent"
config_path="${state_dir}/agent.toml"
binary_path="${state_dir}/svpchain-evm-agent"
pid_path="${state_dir}/agent.pid"
log_path="${state_dir}/agent.log"
build_modfile="${state_dir}/local-build.mod"
build_sumfile="${state_dir}/local-build.sum"

pid_alive() {
  [[ -s "${pid_path}" ]] || return 1
  local pid
  pid="$(<"${pid_path}")"
  [[ -n "${pid}" ]] && kill -0 "${pid}" 2>/dev/null
}

port_from_listen() {
  case "${listen_addr}" in
    *:*) printf '%s' "${listen_addr##*:}" ;;
    *) fail "--listen must be host:port, got ${listen_addr}" ;;
  esac
}

stop_pid() {
  local pid="$1"
  info "stopping pid ${pid}"
  kill "${pid}" 2>/dev/null || true
  for _ in {1..20}; do
    kill -0 "${pid}" 2>/dev/null || break
    sleep 1
  done
  kill -0 "${pid}" 2>/dev/null && fail "pid ${pid} did not stop"
}

resolve_protocol_dir() {
  if [[ -n "${protocol_dir}" ]]; then
    [[ -f "${protocol_dir}/go.mod" ]] || fail "EVM_AGENT_LOCAL_PROTOCOL_DIR is not a protocol module: ${protocol_dir}"
    printf '%s' "${protocol_dir}"
    return
  fi
  local candidate
  for candidate in "${REPO_DIR}/../svpagent/protocol" "${REPO_DIR}/../../svpchain/protocol"; do
    if [[ -f "${candidate}/go.mod" ]]; then
      printf '%s' "${candidate}"
      return
    fi
  done
  fail "protocol checkout not found; set EVM_AGENT_LOCAL_PROTOCOL_DIR"
}

resolve_local_chain_script() {
  if [[ -n "${local_chain_script}" ]]; then
    [[ -f "${local_chain_script}" ]] || fail "EVM_AGENT_LOCAL_CHAIN_SCRIPT does not exist: ${local_chain_script}"
    printf '%s' "${local_chain_script}"
    return
  fi
  printf '%s/scripts/local_node_agents.sh' "$(resolve_protocol_dir)"
}

check_local_chain() {
  curl -fsS --max-time 3 "${comet_rpc}/status" >/dev/null || fail "local chain Comet RPC is unavailable at ${comet_rpc}"
}

render_config() {
  cat <<EOF
# Generated by scripts/local-evm-agent.sh. Do not edit by hand.
listen_addr = "${listen_addr}"
public_url = "${public_url}"

[dex_chain]
id               = "${chain_id}"
grpc_addr        = "${grpc_addr}"
comet_rpc_url    = "${comet_rpc}"
indexer_base_url = "${indexer}"
evm_rpc_url      = "${evm_rpc}"
EOF
}

prepare_build_module() {
  local resolved_protocol
  resolved_protocol="$(resolve_protocol_dir)"
  cp "${REPO_DIR}/go.mod" "${build_modfile}"
  cp "${REPO_DIR}/go.sum" "${build_sumfile}"
  (
    cd "${REPO_DIR}"
    go mod edit -modfile="${build_modfile}" -replace "github.com/dydxprotocol/v4-chain/protocol=${resolved_protocol}"
  )
}

build_binary() {
  GOWORK=off go build -modfile="${build_modfile}" -mod=mod -o "${binary_path}" ./cmd/svpchain-evm-agent
}

case "${mode}" in
  config) render_config; exit 0 ;;
  status)
    if pid_alive; then info "running (pid $(<"${pid_path}"), ${public_url})"; exit 0; fi
    rm -f "${pid_path}"; info "stopped"; exit 1 ;;
  logs) [[ -f "${log_path}" ]] || fail "no log file at ${log_path}"; tail -n 120 -f "${log_path}" ;;
  stop)
    if pid_alive; then stop_pid "$(<"${pid_path}")"; fi
    rm -f "${pid_path}"; info "stopped"; exit 0 ;;
esac

pid_alive && fail "already running (pid $(<"${pid_path}")); use stop first"
script="$(resolve_local_chain_script)"
[[ -f "${script}" ]] || fail "local chain launcher not found: ${script}"
info "ensuring local chain is running via ${script}"
DYDX_HOME="${local_chain_home}" CHAIN_ID="${chain_id}" bash "${script}" start
check_local_chain

mkdir -p "${state_dir}"
render_config > "${config_path}"
if [[ "${skip_build}" == 0 ]]; then
  info "building local binary"
  prepare_build_module
  build_binary
else
  [[ -x "${binary_path}" ]] || fail "--skip-build requested but ${binary_path} is absent"
fi

port="$(port_from_listen)"
info "starting against chain ${chain_id}"
nohup "${binary_path}" -config "${config_path}" >"${log_path}" 2>&1 < /dev/null &
pid=$!
printf '%s\n' "${pid}" > "${pid_path}"
for _ in {1..20}; do
  if ! kill -0 "${pid}" 2>/dev/null; then
    rm -f "${pid_path}"
    tail -n 80 "${log_path}" >&2 || true
    fail "agent exited during startup"
  fi
  if curl -fsS --max-time 2 "http://127.0.0.1:${port}/healthz" >/dev/null 2>&1 && curl -fsS --max-time 2 "http://127.0.0.1:${port}/.well-known/agent-card.json" >/dev/null 2>&1; then
    info "ready"
    info "health: http://127.0.0.1:${port}/healthz"
    info "card:   ${public_url}/.well-known/agent-card.json"
    exit 0
  fi
  sleep 1
done
kill "${pid}" 2>/dev/null || true
rm -f "${pid_path}"
tail -n 80 "${log_path}" >&2 || true
fail "agent readiness check failed after 20 seconds"
